---
##
# Create a new 'trunk' Drupal site on the server.
#
# repo: The github repository
#   eg: git@github.com:fourkitchens/trainingwheels-drupal-files-example.git
# domain_name: The domain name of the site.
#  eg: example.webchef2.com
# db_name: The name of the database to create.
# db_user: The username of the db user.
# db_pass: The password of the db user.
#
- hosts: localhost
  user: root
  connection: local

  tasks:

    - name: Checkout the git repo
      action: git repo=$repo dest=/var/www/vhosts/$domain_name version=master

    - name: Let Bender own the repo.
      action: "command chown -R bender: /var/www/vhosts/$domain_name"

    - name: Create sites/default/files if it doesn't exist ensure it's owned by the www-data user.
      action: file path=/var/www/vhosts/$domain_name/sites/default/files state=directory owner=www-data group=www-data

    - name: Make www-data the owner of all sites/default/files
      action: "command chown -R www-data: /var/www/vhosts/$domain_name/sites/default/files"

    - name: Make a vhost config file.
      action: template src=etc-apache2-sites-available-template.j2 dest=/etc/apache2/sites-available/$domain_name

    - name: Enable our new site
      action: command a2ensite $domain_name creates=/etc/apache2/sites-enabled/$domain_name

    - name: Create MySQL db
      action: mysql_db name=$db_name

    - name: Create MySQL user
      action: mysql_user name=$db_user password=$db_pass priv=$db_name.*:ALL

    - name: Add a drush alias for the site
      action: template src=./etc-drush-alias-template dest=/etc/drush/$domain_name.alias.drushrc.php

    - name: Restart apache2
      action: service name=apache2 state=restarted
