---
# The playbook for common tasks

- include: apt.yml tags=apt
- include: git.yml tags=git
- include: editors.yml tags=editors
- include: etckeeper.yml tags=etckeeper
- include: mc.yml tags=mc
- include: motd.yml tags=motd
- include: ssh.yml tags=ssh
- include: tty.yml tags=tty
- include: hosts.yml tags=hosts
